### ISSUE TITLE
Docs should be included with release

### ISSUE THREAD

**Issue by sshanks-kx** [KxSystems/arrowkdb#17]
New docs folder wont currently be added to a release build - should be included in the future while docs are there.
.travis.yml example area
e.g.
elif [[ $TRAVIS_OS_NAME == "windows" ]]; then
7z a -tzip $FILE_NAME README.md install.bat LICENSE q examples;
elif [[ $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ]]; then
tar -zcvf $FILE_NAME README.md install.sh LICENSE q examples;

**Comment by vgrechin-kx** [comment]
Hi Simon - I'm including your Travis CI patch into the next docs update as a separate commit

**Comment by vgrechin-kx** [comment]
Closing the ticket because the patch is merged.
Simon, thanks for pointing out.
