### ISSUE TITLE
Handle nulls when reading (didn't test writing)

### ISSUE THREAD

**Issue by nugend** [KxSystems/arrowkdb#2]
The library is not respecting the null bitmaps. These could probably be handled using the Compute API to fill in the null KDB values.

**Comment by nugend** [comment]
Before Arrow 6.0, this can be done with the fill_null compute function, 6.0 and greater, it needs to be done with the coalesce compute function.

**Comment by vgrechin-kx** [comment]
Delivered in Release 1.2.0
